### PR TITLE
Created Property Schema and Model and Set up API endpoints

### PR DESCRIPTION
**Pull request by collinsezedike**

### CODE REVIEW

**Comment by collinsezedike** [comment]
The endpoint does not work because the codebase was refactored to app routing.
I am currently doing research on how to go about implementing it with the app router and so far it doesn't seem like it is possible.
Does anyone have experience with it?
@ProCode47 @Agu-Bright @Emmanuetoks

**Comment by collinsezedike** [comment]
I have figured out how to setup the endpoints on the app router.
The only issue is that the get properties endpoint throws an error because the endpoint itself is asynchronous and an asynchronous function inside it

Suggestions online says I have to config the webpack in the next.config file to allow top-level-await but I don't understand it, yet.

**Comment by collinsezedike** [comment]
The changes I made are experimental features so nextjs shows these warnings.

```
- warn You have enabled experimental features (esmExternals, serverComponentsExternalPackages) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
```

Everything works as normal tho.

**Review by Emmanuetoks — APPROVED** [review]
i believe this is the final commit which contains all the changes you have made, because this will be the one i will merge

**Comment by ProCode47** [comment]
I just looked at the code, it looks good and minimal, nice work!
i haven't worked with Next.js but I got mongoose and mongodb knowledge and nothing seems out of place, I couldn't run it tho because there wasn't any env file contaning the database uri, I think since we're still we in development, you could push the env file to the repo as well so others could test.

also are you using mongoDB Atlas or are you running a local instance?

**Review by ProCode47 — APPROVED** [review]

**Review by ProCode47 — APPROVED** [review]

**Comment by collinsezedike** [comment]
> also are you using mongoDB Atlas or are you running a local instance?

A local instance.

**Comment by Emmanuetoks** [comment]
Please try to upload the .env file to files so that the other backend guys can get access to the database

**Comment by collinsezedike** [comment]
> Please try to upload the .env file to files so that the other backend guys can get access to the database

That would not be necessary because there is only one variable in the env file and that is the database URI.

Since it is a local instance, they can create theirs and add their URI.

Plus, we shouldn't be reckless, just because we're still infant.

**Pull request merged**
